services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"

  # REDE INTERNA
networks:
  default:
    driver: bridge